### ISSUE TITLE
大佬您好，请教个问题，如有打扰，还请见谅哈。这个问题我咨询过力鼎，但是感觉解释的不太明白，这两个参数应该和TCP拆包相关，那么应用层如何知道TCP层传输的时候拆了多少个包呢？

### ISSUE THREAD

**Issue by piaoshidefengrunner** [dreamkidd/idea_setting_sync#1]
![image](https://user-images.githubusercontent.com/6898150/56844464-1de62e00-68e3-11e9-96df-6988328e5ef7.png)

![image](https://user-images.githubusercontent.com/6898150/56844536-4ae71080-68e4-11e9-92db-dc52ea4f838c.png)
![image](https://user-images.githubusercontent.com/6898150/56844544-72d67400-68e4-11e9-8abb-cb59f4c4618f.png)
![image](https://user-images.githubusercontent.com/6898150/56844549-94cff680-68e4-11e9-9eea-8da7762dd2db.png)
![image](https://user-images.githubusercontent.com/6898150/56844551-a1544f00-68e4-11e9-8af6-ea0facb73f3f.png)

**Comment by piaoshidefengrunner** [comment]
方便加个微信交流一下么，我看您也在北京哈，咱们这圈子很小，说不定哪天就真的聚一起了呢😀

**Comment by dreamkidd** [comment]
wechat：18193167599
具体的实现细节我记不太清楚了...基本上保温协议在那里 你按字节解析就好了...我现在也不做这块东西了...
沾包拆包的实现是netty实现的 你不用太关注底层实现细节
playload 是我自己封装的pojo
项目源码你需要的话我看我能不能要到了...因为我现在不做这东西了...
